#!/usr/bin/env bash
# OnOffCPA SPA 빌더 dist → onoff-builder-bridge imports 동기화
# 주의: linkconnect 저장소의 SPA 번들을 여기로 복사하면 안 됨(브랜드/카피 분리).
# 반드시 onoffcpa/builder/linkconnect_source 에서 npm run deploy:imports 로만 갱신.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/builder/linkconnect_source/dist"
PUBLIC="$ROOT/builder/linkconnect_source/public"
DEST="$ROOT/plugin/onoff-builder-bridge/imports/linkconnect"
LOCK="$DEST/spa-brand.onoffcpa"

# 교차 저장소 경로 방어: 이 스크립트는 onoffcpa 루트에서만 실행
case "$ROOT" in
  */onoffcpa) ;;
  *)
    echo "sync-linkconnect-builder: REFUSE — ROOT 가 onoffcpa 가 아님: $ROOT" >&2
    echo "  linkconnect 저장소 SPA 를 이 경로로 넣지 마세요." >&2
    exit 1
    ;;
esac

if [[ ! -d "$SRC" ]]; then
  echo "dist 없음. 먼저 실행: cd builder/linkconnect_source && npm run build" >&2
  exit 1
fi

# 소스 dist 부터 브랜드 검증 (잘못된 빌드 동기화 방지; dist 에는 lock 없음)
bash "$ROOT/scripts/assert-onoffcpa-spa-branding.sh" "$SRC/index.html"

mkdir -p "$DEST/assets"
# Built assets (hashed JS/CSS + index.html) — replace
# spa-brand / BRANDING 문서는 --delete 대상에서 제외해 잠금 유지
rsync -a --delete \
  --exclude '._*' \
  --exclude '.DS_Store' \
  --exclude '*.map' \
  --exclude 'spa-brand.onoffcpa' \
  --exclude 'BRANDING.md' \
  "$SRC/assets/" "$DEST/assets/"
cp "$SRC/index.html" "$DEST/index.html"

# Static public assets (favicon, about images, webtoon) — merge, never wipe extras
if [[ -d "$PUBLIC" ]]; then
  rsync -a \
    --exclude '._*' \
    --exclude '.DS_Store' \
    --exclude 'spa-brand.onoffcpa' \
    --exclude 'BRANDING.md' \
    "$PUBLIC/" "$DEST/"
fi

# 브랜드 lock (배포·런타임·CI 가드가 이 파일을 요구)
cat > "$LOCK" <<'EOF'
brand=onoffcpa
# Generated by scripts/sync-linkconnect-builder.sh — do not copy from linkconnect repo.
EOF

find "$DEST" -name '._*' -delete 2>/dev/null || true
find "$DEST" -name '.DS_Store' -delete 2>/dev/null || true

bash "$ROOT/scripts/assert-onoffcpa-spa-branding.sh" --require-lock "$DEST/index.html"

echo "Synced: $SRC -> $DEST"
ls -la "$DEST/assets"
